// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.196
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorWithToolbox2017
{
		static class Vsix
		{
				public const string Id = "cbd91f27-a21c-4dae-9eb0-a7ee8a63f20d";
				public const string Name = "EditorWithToolbox2017";
				public const string Description = @"Empty VSIX Project.";
				public const string Language = "de-DE";
				public const string Version = "1.0";
				public const string Author = "Sakir Kaymakci";
				public const string Tags = "";
		}
}
